problem_1 : 
	gcc problem_1.c -o bin && ./bin

problem_2 : 
	gcc problem_2.c -o bin && ./bin

problem_3 : 
	gcc problem_3.c -o bin && ./bin

problem_4 : 
	gcc problem_4.c -o bin && ./bin

problem_5 : 
	gcc problem_4.c -o bin && ./bin

problem_6 : 
	gcc problem_4.c -o bin && ./bin