challengeA:
	gcc challengeA.c -o bin && ./bin
challengeB:
	gcc challengeB.c -o bin && ./bin
challengeC:
	gcc challengeC.c -o bin && ./bin
challengeD:
	gcc challengeD.c -o bin && ./bin
challengeE:
	gcc challengeE.c -o bin && ./bin
